### ISSUE TITLE
日志级别是否对应不上？

### ISSUE THREAD

**Issue by hpgstar** [GotaX/logrus-aliyun-log-hook#2]
SyslogLevelMapping = func() LevelMapping {
		m := [7]int{0, 2, 3, 4, 6, 7, 8}
		return func(level logrus.Level) int { return m[level] }
	}()

modifier := func(contents map[string]string) {
			level, _ := strconv.Atoi(contents[levelKey])
			contents[levelKey] = strings.ToUpper(logrus.Level(level).String())
		}
info级别会变成 6  转换回来就变成trace

**Comment by hpgstar** [comment]
restoreLogLevelMap := map[int]int{
			0:0, //panic
			2:1, //fatal
			3:2, //error
			4:3, //warning
			6:4, //info
			7:5, //debug
			8:6,  //trace
		}
		modifier := func(contents map[string]string) {
			level, _ := strconv.Atoi(contents[levelKey])
			contents[levelKey] = strings.ToUpper(logrus.Level(restoreLogLevelMap[level]).String())
		}
我在本地维护了这个转换 可以还原level

**Comment by GotaX** [comment]
@hpgstar 因为单元测试里的那个 converter 传入了一个自定义的 LevelMapping，并不是默认值里的 syslog，所以直接照搬会对不上。

有两种解决方案：
1. 把 LevelMapping 换成和单元测试里一样的：`func(level logrus.Level) int { return int(level) }`, modifier 代码不变
2. 把 modifier 改成根据 syslog 做映射：
``` golang
const levelKey = "level"

mLevel := map[string]string{
	"0": "PANIC",
	"2": "FATAL",
	"3": "ERROR",
	"4": "WARNING",
	"6": "INFO",
	"7": "DEBUG",
	"8": "TRACE",
}

modifier := func(contents map[string]string) {
	contents[levelKey] = mLevel[contents[levelKey]]
}
```

**Comment by hpgstar** [comment]
好的  多谢~
